version: '3'

services:
  oidc:
    image: api-oauth/oidc
    ports:
      - "8000:3000"
    environment:
      DEBUG: "oidc-provider:*"

  demo-api:
    image: api-oauth/demo-api
    ports:
      - "8080:3000"

