version: '3'

services:
  oidc:
    image: api-oauth/oidc
    ports:
      - "8000:8000"
    environment:
      DEBUG: "oidc-provider:*"

  demo-api:
    image: api-oauth/demo-api
    environment:
      AUTH_URL: "http://oidc:8000"
    ports:
      - "9000:9000"

  demo-webapp:
    image: nginx:1.17-alpine
    ports:
      - "8080:80"
    volumes:
      - "./demo-webapp/src:/usr/share/nginx/html"

  jwtio:
    image: api-oauth/jwtio
    ports:
      - "9090:80"
