version: '3'

services:
  oidc:
    image: api-oauth/oidc
    ports:
      - "3000:3000"
    environment:
      CLIENT_ID: "demo_app"
      CLIENT_SECRET: "password"
      CALLBACK_URI: "http://demo-api:8080"

  demo-api:
    image: api-oauth/demo-api
    ports:
      - "8000:3000"

